language: erlang
services:
  - mysql
before_script:
  - make -C $TRAVIS_BUILD_DIR/test.ssl
  - cat "$TRAVIS_BUILD_DIR/test.ssl/my-ssl.cnf" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - mysql -uroot -e "grant all privileges on otptest.* to otptest@localhost identified by 'otptest'"
  - mysql -uroot -e "grant all privileges on otptestssl.* to otptestssl@localhost identified by 'otptestssl' require ssl"
script: 'make tests'
otp_release:
  - 19.0
  - 18.3
  - 17.3
  - 17.0
  - R16B03-1
  - R16B
